check:
	echo "Makefile is working fine"

compile:
	echo "Compiling Login.cpp file"
	g++ src/login.cpp -o Login

App:
	./Login
source:
	echo "Displaying login command"
	cat src/login.cpp

admin:
	echo "Displaying admin header file"
	cat header/Admin.h
faculty:
	echo "Display faculty header file"
	cat header/Faculty.h
logincsv:
	echo "Displaying Login csv"
	cat csv/login.csv
datacsv:
	echo "Displaying data csv"
	cat csv/data.csv
allocatecsv:
	echo "Displaying allocate csv"
	cat csv/allocate.csv
testcompile:
	g++ Unit/UnitTesting.cpp -o UnitTesting
testrun:
	./UnitTesting
testcat:
	cat Unit/UnitTesting.cpp